server:
  #对外端口
  port: 9090
  #对外http访问根路径
  servlet:
    contextPath: /

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://128.196.236.7:1521/RCCTY0_CEN00001_28
    username: root
    password: erfG2020

  #支持ansi则彩色输出
  output:
    ansi:
      enabled: detect

#mapper映射文件扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  #日志路径
  file:
    name: ./logfiles/dev/dev.logfiles
  #日志输出格式
  pattern:
    console: '%d{HH:mm:ss} %clr(%-5level){blue} %clr(%logger{32}){cyan} %clr(%msg%n){yellow}'
    file: '%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level%logger{64}%msg%n'
  #日志级别
  level: info