server:
  #对外端口
  port: 9090
  #对外http访问根路径
  servlet:
    contextPath: /

spring:
  profiles:
    active: dev

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true