<#--公共样式-start-->
<link rel="stylesheet" href="/webjars/bootstrap/4.1.0/css/bootstrap.min.css" />
<script src="/webjars/jquery/3.5.1/jquery.min.js"></script>
<script src="/webjars/jquery-cookie/1.4.1/jquery.cookie.js"></script>
<script src="/webjars/popper.js/1.14.1/umd/popper.js"></script>
<script src="/webjars/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/login/base64.js"></script>
<link rel="stylesheet" href="css/comm.css"/>
<#--公共js-end-->