<!doctype html>
<html lang="ch">
<head>
    <meta charset="utf-8">
    <title>主界面</title>

    <#include "../comm/common.ftlh">

</head>
<body>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
    <h3>Hello World!</h3>
</body>
</html>