<!doctype html>
<html lang="ch">
<head>
    <meta charset="utf-8">
    <title>欢迎欢迎！热烈欢迎！</title>
    <link rel="stylesheet" href="css/login.css">
</head>
<body>
<div class="contact-form">
    <img src="/img/login/point.jpg" alt="" class="avatar">
    <h2>来者何人！</h2>
    <form action="">
        <p>账号：</p>
        <input type="user" placeholder="你的账号是啥">
        <p>密码：</p>
        <input type="password" placeholder="输入我悄悄告诉你的密码">
        <input type="submit" value="咻~">
        <p><input type="checkbox">下回来还认得你</p>
    </form>
</div>
</body>
</html>